name: fem
dependencies:
  - python=3.11
  - numpy
  - scipy
  - jupyter
  - flake8
  - pylint
  - pytest
  - pytest-pep8
  - pytest-cov
  - pytest-xdist
  - h5py
  - matplotlib
  - sphinx
  - pip
  - pip:
    - sphinxcontrib-napoleon
    - pyevtk
