#!/usr/bin/perl -w
#
# czdisp - convert double precision zdisp.mat files to single
# precision zdisp.mat files which are ~1/2 the size
#
# Usage: czdisp zdisp.mat
#
# Mark 04/23/05

# what directory is this?
open(PWD,"pwd|");
$StartDir = <PWD>;
close(PWD);
chomp($StartDir);

foreach $dirname (<les*>)
	{
	# swith into each lesion directory
	$FullPath = $StartDir . "/" . $dirname;
	chdir($FullPath);
	print "Working in $FullPath\n";

	# generate a temporary matlab file to execute
	open(FILE,">czdisp.m");
	print FILE "load zdisp.mat\n";
	print FILE "zdisp = single(zdisp);\n";
	print FILE "save zdisp.mat zdisp\n";
	print FILE "quit\n";
	close(FILE);

	# run matlab to convert the file to single precision
	system("matlab -nojvm -nosplash < czdisp.m > czdispjunk");

	# clean things up
	system("rm czdisp.m czdispjunk");
	}
