#!/usr/bin/perl
#
# striptherm
# perl script to take node_temp_t*.asc files that are exported from
# lsprepost, and strip the header from them; only lines with two entries are
# kept
# 
# mark 02/24/04
#

# find all of the node*.asc files in this directory
@therm = <node*.asc>;

$no_files = @therm;

print "stripping the headers from the lsprepost output\n";
print "there are ",$no_files," files to process\n";

foreach $therm (@therm) {
	print $therm," converted to ";

	# read in the next node*.asc file
	@ARGV = ($therm);

	@t = split('_',$therm);
	
	# spit the headerless data into a new file, t*.asc
	open(T, ">@t[2]");

	print @t[2],"\n";

	while (<>) {
		chomp;
		@fields = split(' ',$_);
		if ($#fields == 1) {
			print T $_,"\n";
		}
	}

	# delete the old node*.asc file
	unlink ($therm);

	close(T);
}
