#!/usr/bin/perl
# SpacesToCommas - convert space delimited data to comma
# delimited data
#
# Usage:  SpacesToCommas < spaces.txt > commas.txt
# spaces.txt is the space delimited ASCII file
# commas.txt is the new comma delimited ASCII file
#
# Mark 08/15/05

while(<>) {
	chomp;
	@fields = split(' ',$_);
  print join(",",@fields)."\n";
}
