#!/usr/bin/perl
# LesionCheck - make sure that things ran like I inteded for
# them to run
# Mark 04/17/05

# what directory is this?
open(PWD,"pwd|");
$StartDir = <PWD>;
close(PWD);
chomp($StartDir);

# work on this directory first
system("grep .asc cirs.dyn");

# now work on all of the other directories
@NextDirs = <*mm>;

foreach $NextDir (@NextDirs)
	{
	$FullPath = $StartDir . "/" . $NextDir;
	chdir($FullPath);
	system("grep .asc cirs.dyn");
	}

