# Remove the headers (and footer) from the ASCII files that are
# generated by ls-prepost2
#
# Mark 09/27/05

while(<>) {
	# remove the EOL character from each line
	chomp;

	# split up each line into columns delimited by spaces
  @fields = split(' ',$_);

	if(($#fields+1) == 2) {
		print "@fields\n";
	}
}
