
class DynaMeshWriterMixin:
    def write_nodes(self, node_filename='nodes.dyn', header_comment="$ Generated by"):
        with open(node_filename, 'w') as fh:
            fh.write(f"{header_comment}\n")
            fh.write("*NODE\n")
            fh.write("$ NID, x, y, z, TC, RC\n")

            for nid, x, y, z, tc, rc in self.nodes:
                fh.write(f"{nid},{x:.6f},{y:.6f},{z:.6f},{tc},{rc}\n")
            
            fh.write("*END\n")

        # logger.info(f" {len(nodes)} nodes written to {node_filename}")

    def write_elems(self, elem_filename='elems.dyn', header_comment="$ Generated by"):
        with open(elem_filename, 'w') as fh:
            fh.write(f"{header_comment}\n")
            fh.write("*ELEMENT_SOLID\n")
            fh.write("$ NID, PID, n1, n2, n3, n4, n5, n6, n7, n8\n")

            for nid, pid, n1, n2, n3, n4, n5, n6, n7, n8 in self.elems:
                fh.write(f"{nid},{pid},{n1},{n2},{n3},{n4},{n5},{n6},{n7},{n8}\n")
            
            fh.write("*END\n")

        # logger.info(f" {len(elems)} elements written to {elem_filename}")