name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./fem/post/create_disp_dat_c
    steps:
    - uses: actions/checkout@v2
    - name: create_disp_dat
      run: make create_disp_dat
    - name: create_disp_dat test
      run: make test
