name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./fem/post
    steps:
    - uses: actions/checkout@v2
    - name: generate create_disp_dat and scale_disp_dat Makefile with cmake
      run: cmake .
    - name: make targets
      run: make
    - name: generate create_disp_dat disp.dat output
      run: ./create_disp_dat -i ../../tests/nodout1 -o ./disp.dat
    - name: compare test output
      run: cmp ../../tests/disp.dat.good ./disp.dat ; if [ $$? -eq 0 ] ; then echo "passed test" ; else echo "failed test"; fi; 
