"""test_GenMesh.py

Mark Palmeri
mlp6@duke.edu
2016-01-30
"""

xyz = (0, 2, 3, 5, 6, 8)
numElem = (2, 2, 2)
pos = [[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]]
header_comment = "$Generated by test_GenMesh.py"


def test_calc_node_pos():
    """calculate unique x, y, z positions for the mesh
    """
    from GenMesh import calc_node_pos
    assert calc_node_pos(xyz, numElem) == pos


def test_check_x0_y0():
    """do not pass if 0.0 missing from x or y
    """

    from GenMesh import check_x0_y0
    assert check_x0_y0(pos) != 1

    pos2 = pos
    pos2[1][1] = 0.0
    assert check_x0_y0(pos2) == 0


def test_writeNodes(tmpdir):
    """write test nodes.dyn file
    """
    from GenMesh import writeNodes

    nodefile = "nodes.dyn"
    f = tmpdir.join(nodefile)
    writeNodes(pos, f.strpath, header_comment)
    lines = f.readlines()
    assert lines[0] == header_comment+"\n"
    assert lines[1] == "*NODE\n"
    assert lines[2] == "1,0.000000,3.000000,6.000000\n"
    assert lines[-1] == "*END\n"


def test_writeElems(tmpdir):
    """write test elems.dyn file
    """
    from GenMesh import writeElems

    elefile = "elems.dyn"
    partid = 1
    f = tmpdir.join(elefile)
    writeElems(numElem, partid, f.strpath, header_comment)
    lines = f.readlines()
    assert lines[0] == header_comment+"\n"
    assert lines[1] == "*ELEMENT_SOLID\n"
    assert lines[2] == "1,1,1,2,5,4,10,11,14,13\n"
    assert lines[-1] == "*END\n"
